routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@index')->name('index');

Route::get('/about', function () {
    return view('landing_page.about');
})->name('about');

Route::get('/news', 'PageController@newsPage')->name('news');

Route::get('/promo', 'PageController@promoPage')->name('promo');

Route::get('/contact', 'ContactController@index')->name('contact');
Route::get('/get_branch', 'ContactController@getBranch')->name('contact.get_branch');

Route::get('/services', function () {
    return view('landing_page.services');
})->name('services');

Route::get('/service/claim', function () {
    return view('landing_page.service-eclaim');
})->name('eclaim');

Route::get('/service/complain', function () {
    return view('landing_page.service-ecomplain');
})->name('ecomplain');

Route::get('/service/request', function () {
    return view('landing_page.service-erequest');
})->name('erequest');

Route::get('/news/{slug}', 'PageController@newsDetail')->name('news.detail');

Route::get('/promo/{slug}', 'PageController@promoDetail')->name('promo.detail');

Route::get('/faq', 'FaqController@index')->name('faq');

Route::post('/simulation', 'FormController@creditSimulation')->name('simulation.post');

Route::post('/subscribe', 'FormController@subscribe')->name('subscribe.post');


Route::get('/term-and-conditions', 'PageController@termandcondition')->name('term_and_conditions');

Route::get('/privacy-policy', 'PageController@privacypolicy')->name('privacy_policy');

Route::get('/email_verification', 'PageController@verification')->name('verification');

Route::post('/testApiPost', 'FormController@testApiPost')->name('testApiPost');

app/Models/News.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Config;

class News extends Model
{
    protected $table = 'news';
    protected $primaryKey = 'id_news';

    public function getImageAttribute($value){
        $baseUrl = Config::get('app.base_image_url');
        return $value ? $baseUrl . 'user_files/news_image/' . $value : '';
    }
}

resources/views/landing_page/partials/_faq_nav_menu.blade.php
<div class="services-nav-menu mt-5 bg-white mx-5">
  <ul class="nav nav-pills nav-fill py-3">
    <li class="nav-item py-3">
      <a class="nav-link {{ $service == 'faq' ? 'active' : '' }}" href="{{ route('faq') }}">FAQ</a>
    </li>
    <li class="nav-item py-3">
      <a class="nav-link {{ $service == 'term_and_conditions' ? 'active' : '' }}" href="{{ route('term_and_conditions') }}">TERM & CONDITIONS</a>
    </li>
    <li class="nav-item py-3">
      <a class="nav-link {{ $service == 'privacy_policy' ? 'active' : '' }}" href="{{ route('privacy_policy')}}">PRIVACY POLICY</a>
    </li>
  </ul>
</div>

resources/views/landing_page/partials/_footer.blade.php
<section id="newsletter" class="bg-bright-orange">
  <div class="container">
    <div class="row py-5 d-flex align-items-center">
      <div class="col-md-8 is-white">
        <h3>Connect With Us</h3>
        <p class="mb-0">Dapatkan update produk dan promo terbaru dari kami. Tulis emailmu di sini!</p>
      </div>
      <div class="col-md-4">
        <form action="#">
          {{ csrf_field() }}
          <div class="email-subscription d-flex justify-content-center">
            <input type="email" name="email" class="rounded-pill" placeholder="Email Address" required>
            <button type="submit" class="d-flex align-items-center justify-content-center py-2 px-2 size-7"><i class="fas fa-paper-plane mr-2"></i> Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
<section id="footer" class="bg-gradient-blue is-white">
    <div class="container">
      <div class="row py-5">
        <div class="col-md-4 col-6">
          <h4>PT. Andalan Finance Indonesia Head Office</h4>
          <address>Jalan Sunburst CBD Lot II No. 3, BSD City, Lengkong Gudang, Kec. Serpong, Kota Tangerang Selatan, Banten 15321</address>
          <p><i class="fas fa-phone mr-2"></i> 021 1500 995</p>
          <p><i class="fas fa-envelope mr-2"></i> andalancare@andalanfinance.co.id</p>
        </div>
        <div class="col-md-4 col-6">
          <h4 class="text-center">Follow Us <br> On</h4>
          <div class="text-center">
            @foreach(getSocialMedia() as $item)
              <a href="{{ $item->setting_value ? $item->setting_value : '#' }}" target="_blank">
                @if ($item->setting_key == 'Facebook')  
                  <i class="size-3 mx-2 fab fa-facebook"></i>
                @elseif ($item->setting_key == 'Instagram')
                  <i class="size-3 mx-2 fab fa-instagram"></i>
                @elseif ($item->setting_key == 'Twitter')
                  <i class="size-3 mx-2 fab fa-twitter"></i>
                @elseif ($item->setting_key == 'Youtube')
                  <i class="size-3 mx-2 fab fa-youtube"></i>
                @endif
              </a>
            @endforeach
          </div>
        </div>
        <div class="col-md-4">
          <h4 class="text-center mt-4 mt-md-0">Download Aplikasi Andalanku <br> Sekarang!</h4>
          <div>
            <img src="{{ asset('images/device-p-review.png') }}" class="my-3 mx-auto">
          </div>
          <div class="Download-btns align-items-center">
            <a href="https://play.google.com/store/apps/details?id=id.andalan.andalanku" target="_blank">
              <img src="{{ asset('images/download-btns.png') }}" class="">
            </a>
          </div>
        </div>
        <div class="col-md-12 mt-md-5">
          <h2 class="heading-text size-3 has-line is-medium text-center mt-md-2 mt-5">OUR PARTNER</h2>
          <div class="row d-flex justify-content-center align-items-center">
            @foreach(getPartner() as $item)
                <div class="col-md-2 col-3">
                    <div class="card d-flex justify-content-center align-items-center partner my-md-5 my-2">
                        <a href="{{ $item->url != '' ? $item->url : '#' }}">
                            <img class="img-fluid rounded" src="{{ $item->image }}" alt="">
                        </a>
                    </div>
                </div>
            @endforeach
          </div>
        </div>
        <div class="col-md-12">
          <hr class="is-white">
          <div class="row">
            <div class="col-5 col-md-2 d-flex align-items-center pr-md-5">
              <img src="{{ asset('images/andalan-logo.png') }}" class="mr-md-3" alt="" width="50">
              <img src="{{ asset('images/logo-ojk-2.png') }}" alt="" width="50">
            </div>
            <div class="col-12 col-md-10 footer-link d-flex align-items-center justify-content-end size-7 mt-md-0 mt-3">
              <p class="is-pale-grey mb-0">&copy; © 2020 PT. Andalan Finance Indonesia | All Rights Reserved. | <a href="{{ route('term_and_conditions') }}">Term & Condition</a> | <a href="{{ route('privacy_policy') }}">Privacy Policy</a></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

resources/views/landing_page/partials/_navbar.blade.php
<nav class="navbar navbar-top navbar-expand-sm navbar-dark fixed-top bg-lightblue" id="navbar-top">
    <div class="container">
      <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
          aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{{ route('index') }}"><img src="{{ asset('images/andalan-logo.png') }}" alt="" class="logo"></a>
      <div class="collapse navbar-collapse fade" id="collapsibleNavId">
        <ul class="navbar-nav mx-auto mt-2 mt-lg-0">
          <li class="nav-item active">
            <a class="nav-link" href="{{ route('about') }}">About Us</a>
          </li>
          {{--
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Services
            </a>
            <div class="dropdown-menu fade" aria-labelledby="navbarDropdown">
              <div class="container">
                <div class="row align-items-center py-5">
                  <div class="col">
                    <h3 class="heading-menu">OUR SERVICES</h3>
                  </div>
                  <div class="col">
                    <a href="{{ route('ecomplain') }}" class="dropdown-item">
                      E-COMPLAIN
                      <span class="dropdown-item-desc">Customer Service</span>
                    </a>
                  </div>
                  <div class="col">
                    <a href="{{ route('eclaim') }}" class="dropdown-item">
                      E-CLAIM
                      <span class="dropdown-item-desc">Asuransi</span>
                    </a>
                  </div>
                  <div class="col">
                    <a href="{{ route('erequest') }}" class="dropdown-item">
                      E-REQUEST
                      <span class="dropdown-item-desc">Pengambilan Jaminan</span>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </li>
          --}}
          <li class="nav-item">
            <a class="nav-link" href="{{ route('services') }}">Service & Product</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ route('news') }}">News & Promo</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ route('faq') }}">FAQ</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ route('contact') }}">Contact Us</a>
          </li>
        </ul>
      </div>
      <a id="subscribe" href="javascript:void(0)" class="btn btn-secondary btn-lg" data-toggle="modal" data-target="#joinModal">Gabung</a>
    </div>
  </nav>

resources/views/landing_page/partials/_news_nav_menu.blade.php
<div class="services-nav-menu mt-5 bg-white mx-5">
  <ul class="nav nav-pills nav-fill py-3">
    <li class="nav-item py-3">
      <a class="nav-link {{ $service == 'news' ? 'active' : '' }}" href="{{ route('news') }}">NEWS</a>
    </li>
    <li class="nav-item py-3">
      <a class="nav-link {{ $service == 'promo' ? 'active' : '' }}" href="{{ route('promo') }}">PROMO</a>
    </li>
  </ul>
</div>

resources/views/landing_page/partials/_service_nav_menu.blade.php
<div class="services-nav-menu d-block mt-5 bg-white mx-5">
  <ul class="nav nav-pills nav-fill py-3">
    <li class="nav-item">
      <a class="nav-link {{ $service == 'ecomplain' ? 'active' : '' }}" href="{{ route('ecomplain') }}"><span class="heading-text is-bold d-block">E-CLOMPLAIN</span>Customer Services</a>
    </li>
    <li class="nav-item">
      <a class="nav-link {{ $service == 'eclaim' ? 'active' : '' }}" href="{{ route('eclaim') }}"><span class="heading-text is-bold d-block">E-CLAIM</span>Asuransi</a>
    </li>
    <li class="nav-item">
      <a class="nav-link {{ $service == 'erequest' ? 'active' : '' }}" href="{{ route('erequest') }}"><span class="heading-text is-bold d-block">E-REQUEST</span>Pengambilan Jaminan</a>
    </li>
  </ul>
</div>

resources/views/landing_page/partials/_tab-content-dana.blade.php
<div class="row">
  <div class="col-xs-12 col-md-10 offset-md-1 col-lg-8 offset-lg-2">
    <h3 class="heading-text size-4 is-medium is-greyish-brown has-line py-3 mb-5">Kemudahan Pinjaman Multiguna untuk segala Keperluan dengan bunga bersaing dan proses Pencairan yang cepat.</h3>
    <!-- Tab Content Form -->
    <div class="tab-content__form" {{ $type == 'KMG'  ? 'hidden' : '' }}>
	@php
        $plafond = null;
        $dp_percent = null;
        $dp_rupiah = null;
        $tenor = 3;
        $tenor_slide = 0;
        $region = null;
        $insurance = null;

        if($simulation_result != '' && $type == 'KMG'){
          $plafond = $form_data->plafond;
          $dp_percent = $form_data->dp_percent;
          $dp_rupiah = $form_data->dp_rupiah;
          $tenor = $form_data->tenor;
          $tenor_slide = $form_data->tenor_slide;
          $region = $form_data->region;
          $insurance = $form_data->insurance;
        }
		else {
			$plafond = "";
          $dp_percent = "";
          $dp_rupiah ="";
          $tenor = "";
          $tenor_slide = "";
          $region = "";
          $insurance = "";
		}
      @endphp
      <form action="{{ route('simulation.post') }}" method="post" class="text-left" id="danaForm">
        <div class="form-row">
          <div class="form-group col-sm-12">
            <label for="">JUMLAH PLAFOND</label>
            <div class="input-group input-group-lg">
              <div class="input-group-prepend">
                <span class="input-group-text">Rp</span>
              </div>
              <input type="text" class="form-control" placeholder="Masukan Jumlah Plafond" name="plafond" id="dana_plafond">
            </div>
          </div>
          {{--<div class="form-group col-sm-12">--}}
            {{--<label for="">JAMINAN</label>--}}
            {{--<select class="form-control form-control-lg" name="" id="">--}}
              {{--<option></option>--}}
              {{--<option></option>--}}
            {{--</select>--}}
          {{--</div>--}}
          <div class="form-group col-sm-12">
            <label for="">JANGKA WAKTU</label>
            <select class="form-control form-control-lg" name="tenor" id="dana_tenor">
              <option value="" disabled selected >Pilih Jangka Waktu</option>
              <option value="3">3</option>
              <option value="6">6</option>
              <option value="12">12</option>
              <option value="18">18</option>
              <option value="24">24</option>
              <option value="30">30</option>
              <option value="36">36</option>
              <option value="48">48</option>
            </select>
          </div>
          <div class="form-group col-sm-12">
            <label class="d-flex align-items-center">ASURANSI JAMINAN</label>
            <select class="form-control form-control-lg" name="insurance" id="dana_insurance">
              <option value="" disabled selected>Pilih Asuransi</option>
              <option value="TLO">TLO</option>
              <option value="ARK">All Risk</option>
            </select>
          </div>
          <div class="form-group col-sm-12">
            <label for="">ZONA WILAYAH</label>
            <select class="form-control form-control-lg" name="region" id="dana_region">
              <option value="" disabled selected>Pilih Wilayah Domisili</option>
              <option value="1">Sumatra dan Kepulaunnya</option>
              <option value="2">Jakarta, Banten dan Jawa Barat</option>
              <option value="3">Lainnya</option>
            </select>
          </div>
          <input type="hidden" name="type" value="KMG">
          <input type="hidden" name="dp_percent" value="0">
          <input type="hidden" name="_token" id="csrf-token" value="{{ Session::token() }}" />
          <div class="form-group col-sm-12 text-right">
            <button class="btn btn-secondary btn-lg mt-3" id="dana_btn_submit">HITUNG</button>
          </div>
        </div>
      </form>
      <ul class="list-unstyled mt-3 text-left size-7">
        <li>*Syarat dan ketentuan berlaku.</li>
        <li>*Simulasi merupakan bentuk perkiraan, bukan bentuk terakhir dari angsuran.</li>
        <li>*Harga dan bunga bisa berbeda sesuai dengan ketentuan per daerah.</li>
      </ul>
    </div>
    <!-- End of Tab Content Form -->

    <!-- Tab Content Result -->
    @if ($simulation_result != '' && $type == 'KMG')
    <div class="tab-content__result" id="KMG_content_result">
      <div class="mb-4">
        <label class="d-block text-bold is-azure mb-3">ESTIMASI ANGSURAN BULANAN</label>
        <span class="d-inline-block bg-white-three py-3 px-4 is-rounded-half size-2 is-bordered">Rp. {{ $simulation_result->angsuran}} / Bulan</span>
      </div>
      <div class="mb-4">
        <label class="d-block text-bold is-azure mb-3">JANGKA WAKTU</label>
        <span class="size-2">{{ $simulation_result->tenor }} Bulan</span>
      </div>
      
      <button class="btn btn-secondary btn-lg">HITUNG ULANG</button>

      <ul class="list-unstyled mt-5 text-left size-7">
        <li>*Syarat dan ketentuan berlaku.</li>
        <li>*Simulasi merupakan bentuk perkiraan, bukan bentuk terakhir dari angsuran.</li>
        <li>*Harga dan bunga bisa berbeda sesuai dengan ketentuan per daerah.</li>
      </ul>

      <hr class="my-5">

      <h3 class="heading-text size-4 is-medium is-greyish-brown has-line py-3 mb-5">Ajukan Pembiayaan untuk mendapatkan Mobil Impian anda</h3>
      <div class="col-xs-12 col-sm-8 offset-sm-2">
          <form action="{{ route('subscribe.post') }}"  method="post"  id="usedcarsSubmitRequest">
              <div class="mat-group input-group-lg">
                  <input type="text" class="form-control" name="name" id="usedcars_name" placeholder="Type your name">
              </div>
              <div class="mat-group input-group-lg">
                  <input type="text" class="form-control" name="email" id="usedcars_email" placeholder="Your E-Mail address">
              </div>
              <div class="mat-group input-group-lg">
                  <input type="text" class="form-control" name="phone" id="usedcars_phone" placeholder="Your Phone Number">
              </div>
			  <input type="hidden" name="product" value="DANA TUNAI">
			  <input type="hidden" name="otr" value="0">
			   <input type="hidden" name="plafond" value={{$plafond}}>
			  <input type="hidden" name="dp_percent" value="0">
			  <input type="hidden" name="dp_amount" value="0">
			  <input type="hidden" name="tenor" value={{$tenor}}>
			  <input type="hidden" name="insurance" value={{$insurance}}>
			  <input type="hidden" name="region" value={{$region}}>
	  <input type="hidden" name="_token" id="csrf-token" value="{{ Session::token() }}" />
              <button class="btn btn-secondary btn-lg mt-4" id="newcars-submitnow-btn">AJUKAN SEKARANG</button>
          </form>
      </div>

    </div>
    @endif
    <!-- End of Tab Content Result -->
  </div>
</div>

resources/views/landing_page/partials/_tab-content-ecommerce.blade.php
<div class="row">
  <div class="col-xs-12 col-sm-8 offset-sm-2">
    <h3 class="heading-text size-4 is-medium is-greyish-brown has-line py-3 mb-5">Pembiayaan Melalui Market Place</h3>
    <!-- Tab Content Form -->
    <div class="tab-content__form">
      <form action="#" class="text-left">
        <div class="form-row">
          <div class="form-group col-sm-12">
            <label for="">HARGA PRODUK</label>
            <div class="input-group input-group-lg">
              <div class="input-group-prepend">
                <span class="input-group-text">Rp</span>
              </div>
              <input type="text" class="form-control" placeholder="Masukan Harga OTR Mobil">
            </div>
          </div>
          <div class="form-group col-sm-4 col-xs-12">
            <label for="">UANG MUKA</label>
            <select class="form-control form-control-lg" name="" id="">
              <option>...%</option>
              <option></option>
              <option></option>
            </select>
          </div>
          <div class="form-group col-sm-8 col-xs-12">
            <label for="">&nbsp;</label>
            <div class="input-group input-group-lg">
              <div class="input-group-prepend">
                <span class="input-group-text">Rp</span>
              </div>
              <input type="text" class="form-control" placeholder="Masukan Uang Muka">
            </div>
          </div>
          <div class="form-group col-sm-12">
            <label for="">JANGKA WAKTU</label>
            <select class="form-control form-control-lg" name="" id="">
              <option>Pilih Jangka Waktu</option>
              <option></option>
              <option></option>
            </select>
          </div>
          <div class="form-group col-sm-12">
            <label for="">ZONA WILAYAH</label>
            <select class="form-control form-control-lg" name="" id="">
              <option>Pilih Wilayah Domisili</option>
              <option></option>
              <option></option>
            </select>
          </div>
          <div class="form-group col-sm-12 text-right">
            <button class="btn btn-secondary btn-lg mt-3" type="submit">HITUNG</button>
          </div>
        </div>
      </form>
      <ul class="list-unstyled mt-3 text-left size-7">
        <li>*Syarat dan ketentuan berlaku.</li>
        <li>*Simulasi merupakan bentuk perkiraan, bukan bentuk terakhir dari angsuran.</li>
        <li>*Harga dan bunga bisa berbeda sesuai dengan ketentuan per daerah.</li>
      </ul>
    </div>
    <!-- End of Tab Content Form -->

    <!-- Tab Content Result -->
    <div class="tab-content__result" hidden>
      <div class="mb-4">
        <label class="d-block text-bold is-azure mb-3">ESTIMASI ANGSURAN BULANAN</label>
        <span class="d-inline-block bg-white-three py-3 px-4 is-rounded-half size-2 is-bordered">Rp. 3.324.973 / Bulan</span>
      </div>
      <div class="mb-4">
        <label class="d-block text-bold is-azure mb-3">JANGKA WAKTU</label>
        <span class="size-2">60 Bulan</span>
      </div>
      
      <button class="btn btn-secondary btn-lg">HITUNG ULANG</button>

      <ul class="list-unstyled mt-5 text-left size-7">
        <li>*Syarat dan ketentuan berlaku.</li>
        <li>*Simulasi merupakan bentuk perkiraan, bukan bentuk terakhir dari angsuran.</li>
        <li>*Harga dan bunga bisa berbeda sesuai dengan ketentuan per daerah.</li>
      </ul>

      <hr class="my-5">

      <h3 class="heading-text size-4 is-medium is-greyish-brown has-line py-3 mb-5">Ajukan Pembiayaan untuk mendapatkan Mobil Impian anda</h3>
      <div class="col-xs-12 col-sm-8 offset-sm-2">
        <form action="#" class="mat-form" id="danaForm">
          <div class="mat-group input-group-lg">
            <input type="text" class="form-control" id="">
            <label>Nama Lengkap Sesuai KTP</label>
          </div>
          <div class="mat-group input-group-lg">
            <input type="text" class="form-control">
            <label>No Handphone</label>
          </div>
          <div class="mat-group input-group-lg">
            <input type="text" class="form-control">
            <label>Alamat Domisili</label>
          </div>
          <div class="mat-group input-group-lg">
            <select name="" id="" class="form-control">
              <option value=""></option>
            </select>
            <label>Area Domisili</label>
          </div>
          <div class="mat-group input-group-lg">
            <select name="" id="" class="form-control">
              <option value=""></option>
            </select>
            <label>Cabang Andalan</label>
          </div>
          <div class="mat-group input-group-lg">
            <select name="" id="" class="form-control">
              <option value=""></option>
            </select>
            <label>Pilihan watu disurvey</label>
          </div>
          <div class="mat-group input-group-lg">
            <input type="text" class="form-control">
            <label>Alamat Domisili</label>
          </div>
          <button class="btn btn-secondary btn-lg mt-4">AJUKAN SEKARANG</button>
        </form>
      </div>

    </div>
    <!-- End of Tab Content Result -->
  </div>
</div>

resources/views/landing_page/partials/_tos_nav_menu.blade.php
<div class="services-nav-menu mt-5 bg-white mx-5">
  <ul class="nav nav-pills nav-fill py-3">
    <li class="nav-item py-3">
      <a class="nav-link {{ $service == 'tos' ? 'active' : '' }}" href="{{ route('tos') }}">TERM & CONDITIONS</a>
    </li>
    <li class="nav-item py-3">
      <a class="nav-link {{ $service == 'privacy' ? 'active' : '' }}" href="{{ route('privacy') }}">PRIVACY POLICY</a>
    </li>
  </ul>
</div>